title: Sai Krishna Charan Dara # your name (or website title) here
logo: "/images/Logo_Charan.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://saikrishnacharan.github.io/Home">Home</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Education">Education</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Experience">Experience</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Publication">Publications</a>
  <br>
  <a href="https://saikrishnacharan.github.io/ResearchProjects">ResearchProjects</a>
  <br>
  <a href="https://saikrishnacharan.github.io/CourseProjects">Course Projects</a>
  <br>
  <a href="https://saikrishnacharan.github.io/ResearchBlog">Research Blog</a>
  <br>  
  <br>
  <a href="https://www.linkedin.com/in/sai-krishna-charan-dara-63646a1a9/">View My LinkedIn Profile</a>


  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
