title: Sai Krishna Charan Dara # your name (or website title) here
logo: "/images/Logo_Circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://saikrishnacharan.github.io/Home">Home</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Education">Education</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Experience">Experience</a>
  <br>
  <a href="https://saikrishnacharan.github.io/Publication">Publications</a>
  <br>
  <a href="https://saikrishnacharan.github.io/ResearchProjects">ResearchProjects</a>
  <br>
  <a href="https://saikrishnacharan.github.io/CourseProjects">Course Projects</a>
  <br>
  <a href="https://saikrishnacharan.github.io/ResearchBlog">Research Blog</a>
  <br>  
  <br>
  <a href="https://www.linkedin.com/in/sai-krishna-charan-dara-63646a1a9/">View My LinkedIn Profile</a>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-2S9KDZF13Y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2S9KDZF13Y');
</script>

  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
